{
 "title": "Energy consumption",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Energy consumption (in Watt)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_power", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current (in Ampere)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "current", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Voltage (in Volts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "voltage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Temperature (in Celsius)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "temperature", "legendFormat": "{{job}}" }
   ]
  }
 ]
}