global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: "1-plug"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/api/v1/energyconsumption/10.0.1.1"

  - job_name: "2-plug"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/api/v1/energyconsumption/10.0.1.2"

  - job_name: "3-plug"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/api/v1/energyconsumption/10.0.1.3"

  - job_name: "4-plug"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/api/v1/energyconsumption/10.0.1.4"

  - job_name: "5-plug"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/api/v1/energyconsumption/10.0.1.5"

